build(lint-staged): bump lint-staged from 15.4.1 to 15.5.1 (#222)
Bumps [lint-staged](https://github.com/lint-staged/lint-staged) from
15.4.1 to 15.5.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/lint-staged/lint-staged/releases">lint-staged's
releases</a>.</em></p>
<blockquote>
<h2>v15.5.1</h2>
<h3>Patch Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1533">#1533</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/5d535349958a939cd17d87180196bb2b9dfc452b"><code>5d53534</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Improve listing of staged files so that <em>lint-staged</em> doesn't
crash when encountering an uninitialized submodule. This should result
in less errors like:</p>
<pre><code>✖ Failed to get staged files!
</code></pre>
</li>
</ul>
<h2>v15.5.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1526">#1526</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Lint-staged no longer resets to the original state when preventing an
empty git commit. This happens when your configured tasks reset all the
staged changes, typically when trying to commit formatting changes which
conflict with your linter setup like ESLint or Prettier.</p>
<h3>Example with Prettier</h3>
<p>By default Prettier <a
href="https://prettier.io/docs/rationale#strings">prefers double
quotes</a>.</p>
<h4>Previously</h4>
<ol>
<li>Stage <code>file.js</code> with only double quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails,
cancels the commit, and resets back to the original state</li>
<li>Commit was not done, original state is restored and single quotes
<code>'</code> are staged</li>
</ol>
<h4>Now</h4>
<ol>
<li>Stage <code>file.js</code> with only double-quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails and
cancels the commit</li>
<li>Commit was not done, and there are no staged changes</li>
</ol>
</li>
</ul>
<h2>v15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a>
Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>!
- Adjust TypeScript types for the default export so that it can be used
as a value without error TS2693.</li>
</ul>
<h2>v15.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1509">#1509</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Change <em>lint-staged</em>'s dependencies to use <a
href="https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004">caret
(<code>^</code>) ranges</a> instead of <a
href="https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1">tilde
(<code>~</code>)</a>. This makes it easier for package managers to
perform dependency management when minor-level updates are also
permitted instead of just patch-level.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/lint-staged/lint-staged/blob/main/CHANGELOG.md">lint-staged's
changelog</a>.</em></p>
<blockquote>
<h2>15.5.1</h2>
<h3>Patch Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1533">#1533</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/5d535349958a939cd17d87180196bb2b9dfc452b"><code>5d53534</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Improve listing of staged files so that <em>lint-staged</em> doesn't
crash when encountering an uninitialized submodule. This should result
in less errors like:</p>
<pre><code>✖ Failed to get staged files!
</code></pre>
</li>
</ul>
<h2>15.5.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1526">#1526</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Lint-staged no longer resets to the original state when preventing an
empty git commit. This happens when your configured tasks reset all the
staged changes, typically when trying to commit formatting changes which
conflict with your linter setup like ESLint or Prettier.</p>
<h3>Example with Prettier</h3>
<p>By default Prettier <a
href="https://prettier.io/docs/rationale#strings">prefers double
quotes</a>.</p>
<h4>Previously</h4>
<ol>
<li>Stage <code>file.js</code> with only double quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails,
cancels the commit, and resets back to the original state</li>
<li>Commit was not done, original state is restored and single quotes
<code>'</code> are staged</li>
</ol>
<h4>Now</h4>
<ol>
<li>Stage <code>file.js</code> with only double-quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails and
cancels the commit</li>
<li>Commit was not done, and there are no staged changes</li>
</ol>
</li>
</ul>
<h2>15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a>
Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>!
- Adjust TypeScript types for the default export so that it can be used
as a value without error TS2693.</li>
</ul>
<h2>15.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1509">#1509</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Change <em>lint-staged</em>'s dependencies to use <a
href="https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004">caret
(<code>^</code>) ranges</a> instead of <a
href="https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1">tilde
(<code>~</code>)</a>. This makes it easier for package managers to
perform dependency management when minor-level updates are also
permitted instead of just patch-level.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/6a73e5b843567dae42562d7cbc034edf1297f129"><code>6a73e5b</code></a>
chore(changeset): release</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/cf7f1a58b9d8133f2ede9a80d1e94b1b155e3808"><code>cf7f1a5</code></a>
Merge pull request <a
href="https://redirect.github.com/lint-staged/lint-staged/issues/1533">#1533</a>
from lint-staged/fix-submodules-filter</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/6acd5bfa1eac0817c2c88def9be96dd8290825c1"><code>6acd5bf</code></a>
ci: bump Cygwin action v5</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/5d535349958a939cd17d87180196bb2b9dfc452b"><code>5d53534</code></a>
fix: handle uninitialized submodules when listing staged files</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/ccf8fa581d6d50395557f581ee70bf07ee1b34df"><code>ccf8fa5</code></a>
docs(package): fix repository url and bin; add homepage and bugs urls
(<a
href="https://redirect.github.com/lint-staged/lint-staged/issues/1532">#1532</a>)</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/7e6abe47c2c7584e72ded13a16d2e93d0a98f57b"><code>7e6abe4</code></a>
chore(changeset): release</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/0ebfa69f49a8c3335a07bb6a170b5700776ef52d"><code>0ebfa69</code></a>
build(deps): update dependencies</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a>
feat: do not reset to original state when preventing empty commit</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/7b8be705e29c9ec91964d0b12e6c732789a00476"><code>7b8be70</code></a>
chore: update default branch references from &quot;master&quot; to
&quot;main&quot;</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/362a78df9ccb0fe8515c42164f93adaa87469954"><code>362a78d</code></a>
docs: add workaround for tsc ignoring tsconfig.json issue to README FAQ
(<a
href="https://redirect.github.com/lint-staged/lint-staged/issues/1523">#1523</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/lint-staged/lint-staged/compare/v15.4.1...v15.5.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=lint-staged&package-manager=npm_and_yarn&previous-version=15.4.1&new-version=15.5.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

You can trigger a rebase of this PR by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

> **Note**
> Automatic rebases have been disabled on this pull request as it has
been open for over 30 days.

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>